ssh_user=faito_backend_api
public_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFCqTTCx7Vlv9qAeWzGYzGPaevObEfxxef2Qm+WMQM3

service_name=faito_backend_api

# host y puerto en el servidor
api_host=127.0.0.1
api_port=3501

api_cors_origin=*