<?php
declare(strict_types=1);

namespace labo86\escripta;

use RuntimeException;

class AgentGuideInstaller
{
    public const GUIDE_RELATIVE_PATH = '.escripta/ESCRIPTA_AGENTS.md';
    public const HINT_RELATIVE_PATH = '.escripta/AGENTS_HINT.md';

    private const GUIDE_BEGIN_MARKER = '<!-- BEGIN ESCRIPTA AGENT GUIDE -->';
    private const GUIDE_END_MARKER = '<!-- END ESCRIPTA AGENT GUIDE -->';

    public static function isRequested(array $argv): bool
    {
        return in_array('--install-agent-guide', $argv, true);
    }

    public static function run(array $argv): void
    {
        global $escriptaVersion;

        $force = in_array('--force', $argv, true);
        $sourcePath = dirname(__DIR__) . '/resources/ESCRIPTA_AGENTS.md';
        $guide = file_get_contents($sourcePath);

        if ($guide === false) {
            throw new RuntimeException("No se pudo leer la guia de agentes embebida.");
        }

        $cwd = getcwd();
        if ($cwd === false) {
            throw new RuntimeException("No se pudo resolver el directorio actual.");
        }

        $version = is_string($escriptaVersion ?? null) && trim($escriptaVersion) !== ''
            ? $escriptaVersion
            : 'unknown';
        $result = self::install($cwd, $guide, $force, $version);

        echo "Guia de agentes instalada: {$result['guide_path']}\n";
        echo "Hint para AGENTS.md: {$result['hint_path']}\n";
        echo "Version de Escripta: {$version}\n";
        echo self::agentHint() . "\n";
    }

    /**
     * @return array{guide_path: string, hint_path: string}
     */
    public static function install(
        string $targetRepositoryDir,
        string $guideContent,
        bool $force = false,
        string $version = 'unknown'
    ): array
    {
        $targetRepositoryDir = rtrim($targetRepositoryDir, DIRECTORY_SEPARATOR);
        $escriptaDir = $targetRepositoryDir . DIRECTORY_SEPARATOR . '.escripta';

        if (!is_dir($escriptaDir) && !mkdir($escriptaDir, 0775, true) && !is_dir($escriptaDir)) {
            throw new RuntimeException("No se pudo crear el directorio [.escripta].");
        }

        $guidePath = $targetRepositoryDir . DIRECTORY_SEPARATOR . self::GUIDE_RELATIVE_PATH;
        $hintPath = $targetRepositoryDir . DIRECTORY_SEPARATOR . self::HINT_RELATIVE_PATH;
        $managedGuide = self::managedGuide($guideContent, $version);

        self::writeGuide($guidePath, $managedGuide, $force);
        self::writeHint($hintPath, $version);

        return [
            'guide_path' => $guidePath,
            'hint_path' => $hintPath,
        ];
    }

    public static function agentHint(): string
    {
        return 'Read `.escripta/ESCRIPTA_AGENTS.md` when touching Escripta config, generated env vars, or scripts that consume `ESCRIPTA_*`.';
    }

    private static function managedGuide(string $guideContent, string $version): string
    {
        return self::GUIDE_BEGIN_MARKER . "\n"
            . "Generated by Escripta version: {$version}\n\n"
            . rtrim($guideContent, "\r\n") . "\n"
            . self::GUIDE_END_MARKER . "\n";
    }

    private static function writeGuide(string $guidePath, string $managedGuide, bool $force): void
    {
        if (!is_file($guidePath)) {
            file_put_contents($guidePath, $managedGuide);
            return;
        }

        $existing = file_get_contents($guidePath);
        if ($existing === false) {
            throw new RuntimeException("No se pudo leer [$guidePath].");
        }

        if ($existing === $managedGuide) {
            return;
        }

        if (str_contains($existing, self::GUIDE_BEGIN_MARKER) && str_contains($existing, self::GUIDE_END_MARKER)) {
            $updated = preg_replace(
                '/' . preg_quote(self::GUIDE_BEGIN_MARKER, '/') . '.*?' . preg_quote(self::GUIDE_END_MARKER, '/') . '\R?/s',
                $managedGuide,
                $existing,
                1
            );

            file_put_contents($guidePath, $updated ?? $managedGuide);
            return;
        }

        if (!$force) {
            throw new RuntimeException("Ya existe una guia no administrada en [$guidePath]. Usa --force para reemplazarla.");
        }

        file_put_contents($guidePath, $managedGuide);
    }

    private static function writeHint(string $hintPath, string $version): void
    {
        $content = "# Escripta Agent Guide Hint\n\n"
            . "Generated by Escripta version: {$version}\n\n"
            . "Add this line to `AGENTS.md` or the repository's agent entrypoint:\n\n"
            . self::agentHint() . "\n";

        file_put_contents($hintPath, $content);
    }
}
