<?php
declare(strict_types=1);

namespace labo86\escripta\tests;

use labo86\escripta\AgentGuideInstaller;
use PHPUnit\Framework\TestCase;
use RuntimeException;

class AgentGuideInstallerTest extends TestCase
{
    private string $targetDir;

    protected function setUp(): void
    {
        $this->targetDir = tempnam(__DIR__, 'agent_guide_target');
        unlink($this->targetDir);
        mkdir($this->targetDir);
    }

    protected function tearDown(): void
    {
        exec(sprintf('rm -rf %s', escapeshellarg($this->targetDir)));
    }

    public function testInstallCreatesGuideAndHint(): void
    {
        AgentGuideInstaller::install($this->targetDir, "# Guide\n", false, 'v9.8.7');

        $guide = file_get_contents($this->targetDir . '/.escripta/ESCRIPTA_AGENTS.md');
        $hint = file_get_contents($this->targetDir . '/.escripta/AGENTS_HINT.md');

        $this->assertIsString($guide);
        $this->assertStringContainsString('<!-- BEGIN ESCRIPTA AGENT GUIDE -->', $guide);
        $this->assertStringContainsString('Generated by Escripta version: v9.8.7', $guide);
        $this->assertStringContainsString("# Guide\n", $guide);
        $this->assertStringContainsString('<!-- END ESCRIPTA AGENT GUIDE -->', $guide);

        $this->assertIsString($hint);
        $this->assertStringContainsString('Generated by Escripta version: v9.8.7', $hint);
        $this->assertStringContainsString('Read `.escripta/ESCRIPTA_AGENTS.md`', $hint);
        $this->assertStringContainsString('AGENTS.md', $hint);
    }

    public function testInstallUpdatesManagedGuideIdempotently(): void
    {
        AgentGuideInstaller::install($this->targetDir, "# Guide v1\n", false, 'v1.0.0');
        AgentGuideInstaller::install($this->targetDir, "# Guide v2\n", false, 'v2.0.0');
        $firstRun = file_get_contents($this->targetDir . '/.escripta/ESCRIPTA_AGENTS.md');

        AgentGuideInstaller::install($this->targetDir, "# Guide v2\n", false, 'v2.0.0');
        $secondRun = file_get_contents($this->targetDir . '/.escripta/ESCRIPTA_AGENTS.md');

        $this->assertSame($firstRun, $secondRun);
        $this->assertStringNotContainsString('Guide v1', $secondRun);
        $this->assertStringNotContainsString('v1.0.0', $secondRun);
        $this->assertStringContainsString('Guide v2', $secondRun);
        $this->assertStringContainsString('v2.0.0', $secondRun);
    }

    public function testInstallDoesNotOverwriteUnmanagedGuideWithoutForce(): void
    {
        mkdir($this->targetDir . '/.escripta');
        file_put_contents($this->targetDir . '/.escripta/ESCRIPTA_AGENTS.md', "# Local guide\n");

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('guia no administrada');

        AgentGuideInstaller::install($this->targetDir, "# Release guide\n");
    }

    public function testInstallCanOverwriteUnmanagedGuideWithForce(): void
    {
        mkdir($this->targetDir . '/.escripta');
        file_put_contents($this->targetDir . '/.escripta/ESCRIPTA_AGENTS.md', "# Local guide\n");

        AgentGuideInstaller::install($this->targetDir, "# Release guide\n", true);

        $guide = file_get_contents($this->targetDir . '/.escripta/ESCRIPTA_AGENTS.md');

        $this->assertStringNotContainsString('Local guide', $guide);
        $this->assertStringContainsString('Release guide', $guide);
    }
}
