<?php
declare(strict_types=1);

namespace labo86\action_scripts;


class Escript {

  const LANG = 'lang';
  const PARAMS = 'params';
  const CONTENT = 'content';

/**
 * si la linea hace match con una linea que empieza con tres backtics y despues solo espacios
 * @param string $line
 * @return bool
 */
    static function isLineCodeEnd(string $line): bool
    {
        return preg_match('/^```\s*$/', $line) === 1;
    }


    /**
     * si la linea coincides con tres backticks seguida por una palabra despues la palabra escripts y despues parametros de la forma name=value separador por espacios
     * @param string $line
     * @return array{lang: string, params : array }|bool
     */
    static function isLineCodeStart(string $line): array|bool
    {
        if ( preg_match('/^```([a-zA-Z0-9_]+)\s+escript(\s+.*)?$/', $line, $matches) === 1 ) {

            $parameters = $matches[2];
            if ( is_null($parameters) ) {
                $parameters = '';
            } else {
                $parameters = trim($parameters);
            }
            if ( $parameters === '' ) {
                $parameters = [];
            } else {
                $parameters = explode(' ', $parameters);
                $parameters = array_map(function($item) {
                    $item = explode('=', $item);
                    if ( count($item) === 1 ) {
                        $item = [$item[0], true];
                    }
                    return $item;
                }, $parameters);
                $parameters = array_combine(array_column($parameters, 0), array_column($parameters, 1));
            }

            return [
                self::LANG => $matches[1],
                self::PARAMS => $parameters
            ];
        } else {
            return false;
        }
    }

    /**
     * Returns and object that is the param of processBlock
     * @param string $text
     * @return array{lang: string, params : array, content: string}[]

     */
    static function getCodeBlockList(string $text) : array {
        $lines = explode("\n", $text);
        $codeBlockList = [];
        $currentCodeBlock = null;
        foreach ( $lines as $line ) {
            if ( is_null($currentCodeBlock) ) {
                if ( ($newCodeBlock = self::isLineCodeStart($line)) !== false ) {
                    $newCodeBlock[self::CONTENT] = '';
                    $currentCodeBlock = $newCodeBlock;
                }
            } else {
                if ( self::isLineCodeEnd($line) ) {
                    $codeBlockList[] = $currentCodeBlock;
                    $currentCodeBlock = null;
                } else {
                    $currentCodeBlock[self::CONTENT] .= $line . "\n";
                }
            }
        }
        return $codeBlockList;
    }

    /**
     * @param array{lang: string, params : array, content: string} $block
     * @return string
     * @throws \Exception
     */
    static function processBlock(array $block) : string {
        if ( $block['lang'] === 'bash' ) {
            $content = <<<EOF
#!/bin/bash
# This script is generated by escript
EOF;
            foreach ( $block['params'] as $key => $value ) {
                $content .= "\n# $key=$value";
            }

            $content .= "\n\n" . $block['content'];

        } else if ( $block['lang'] === 'php' ) {
            $content = <<<EOF
#!/usr/bin/php
<?php
declare(strict_types=1);

// This script is generated by escript
EOF;

            foreach ( $block['params'] as $key => $value ) {
                $content .= "\n// $key=$value";
            }

            $content .= "\n\n?>" . $block['content'];
        } else {
            $content = <<<EOF
#!/usr/bin/cat
EOF;

            $content .= $block['content'];


        }
        return $content;
    }

    /**
     * @param array $blockParams
     * @return string
     */
    static function generateFileName(array $block) : string {

        $blockParams = $block['params'];
        $name = $blockParams['name'] ?? $blockParams['original'] ?? 'script';
        $name = preg_replace('/[^a-zA-Z0-9_]/', '_', $name);
        $name .= '.escript';

        if ( $block['lang'] === 'php' ) {
            $name .= '.php';
        } else if ( $block['lang'] === 'bash' ) {
            $name .= '.sh';
        } else {
            $name .= '.txt';
        }
        return $name;

    }

    static function mergeBlock(array $block, array $refBlock) : array {
        $mergedBlock = array_merge($block, $refBlock);
        $mergedBlock['content'] = $block['content'];
        return $mergedBlock;
    }

    static function processFolderByCommandLine() {

        global $argv;
        if ( count($argv) !== 2 ) {
            echo "Usage: php escript.php <folder>\n";
            exit(1);
        }

        $folder = $argv[1];

        if ( !is_dir($folder) ) {
            echo "Folder $folder does not exist\n";
            exit(1);
        }

        {
            echo "Removing old scripts\n";

            //delete all files that match the pattern
            foreach (glob("$folder/*.escript.*") as $file) {
                unlink($file);
            }

            passthru("rm $folder/*.escript -rf");
            passthru("rm $folder/files -rf");
            passthru("rm $folder/*.md -rf");
        }

        $codeBlockList = [];
        {
            echo "Translating md.php files\n";

            foreach (glob("$folder/*.md.php") as $file) {

                $outputFile = "$folder/" . basename($file, '.php');
                echo "Translating $outputFile\n";
                passthru("php $file > $outputFile");

                $markdown = file_get_contents($outputFile);


                array_push($codeBlockList, ...Escript::getCodeBlockList($markdown));
            }
        }

        {
            $storedBlockList = [];


            $i = 1;
            foreach ($codeBlockList as $block) {

                if ( $block['params']['id'] ?? false ) {
                    $id = $block['params']['id'];
                    $storedBlockList[$id] = $block;
                }

                $targetFolder = $folder;
                if (isset($block['params']['dir'])) {
                    $dir = $block['params']['dir'] . ".escript";
                    $targetFolder = "$folder/$dir";
                    if (!is_dir($targetFolder)) {
                        mkdir($targetFolder);
                    }
                }

                if ($block['params']['file'] ?? false) {
                    $targetFolder = "$targetFolder/files";
                    if (!is_dir($targetFolder)) {
                        mkdir($targetFolder);
                    }
                    $fileName = $block['params']['name'];
                    $filePath = "$targetFolder/$fileName";
                    file_put_contents($filePath, $block['content']);
                    echo "Copying file $fileName\n";

                } else {

                    if ( isset($block['params']['ref']) ) {
                        $ref = $block['params']['ref'];
                        if ( !isset($storedBlockList[$ref]) ) {
                            echo "Reference $ref not found\n";
                        }
                        $refBlock = $storedBlockList[$ref];
                        $block = Escript::mergeBlock($block, $refBlock);
                    }

                    $numberPrefix = str_pad((string)$i, 2, '0', STR_PAD_LEFT);
                    $scriptName = Escript::generateFileName($block);
                    $scriptContent = Escript::processBlock($block);

                    echo "Generating $numberPrefix.$scriptName\n";
                    $fileName = "$numberPrefix.$scriptName";
                    $filePath = "$targetFolder/$fileName";

                    file_put_contents($filePath, $scriptContent);
                    chmod($filePath, 0755);
                    $i++;
                }
            }
        }
    }
}